# Generated by Django 5.2.3 on 2025-07-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0002_rename_name_user_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
