# Generated by Django 5.2.3 on 2025-06-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('post', models.CharField(max_length=200)),
            ],
        ),
    ]
